# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01bbbf1fc84201ca25c3565d78c30f1edf152ac9be86c4cb3659fd3b55217350d8d175417e62071b37e3e11a32d67e8ed655755a205bcb062f30a5ad6c1a3528

test:
  secret_key_base: df01dfe1b74f6fac21a3e60456ef80d368534946a70e88982a4c14f2aaa817b951d3001eab2241ba9269de75f03c1a23ebd651a9bbdef4ecd8f6560f14137102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
